version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dj-quotes-api
    command: bash -c "python src/manage.py runserver 0.0.0.0:8010"
    volumes:
      - ./src:/app/src
    ports:
      - 8010:8010
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    container_name: dj-quotes-api-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=258456
      - POSTGRES_DB=quote_db
    ports:
      - 5434:5434