"""
Django settings for quote project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from quote.settings.base import *
from quote.settings.database import *
from quote.settings.apps import *
from quote.settings.settings import *
